### ISSUE TITLE
Add possibility to remove all snapshots by aggregate type

### ISSUE THREAD

**Issue by prolic** [prooph/snapshot-store#3]
Should we add a new method

`SnapShotStore::removeAll(string $aggregateType): void` ?

This would also allow the Snapshot Read Model to be reset, see https://github.com/prooph/snapshotter/blob/develop/src/SnapshotReadModel.php#L110

/cc @codeliner @basz @oqq @bweston92

**Comment by codeliner** [comment]
sounds good

**Comment by oqq** [comment]
We should provide all methods from ReadModel interface..

**Comment by prolic** [comment]
I think this would be too much and confusing what to do with this.
